# -*- coding: utf-8 -*-
"""example2_dash.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NYdj_1hoTeYhszgyGu1-lhvwQ9eT6P-f
"""

import streamlit as st

st.write ('Hello, *World!* :sunglasses:')